apiVersion: v1
kind: Service
metadata:
  name: laa-data-claims-certificated-api-uat-postgresql
  namespace: laa-data-claims-certificated-api-uat
  annotations:
    "helm.sh/resource-policy": keep
    "meta.helm.sh/release-name": "shared"
    "meta.helm.sh/release-namespace": "laa-data-claims-certificated-api-uat"
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    run: port-forward-pod
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster

